name: peek_and_pop
description: Peek & Pop implementation for Flutter based on the iOS functionality of the same name.
version: 0.2.0
author: Ali Yigit Bireroglu <aliyigitbireroglu@gmail.com>
repository: https://github.com/aliyigitbireroglu/flutter-peek-and-pop
homepage: https://www.cosmossoftware.coffee

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  transparent_image: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

